export const lnList = {
    'AVOP': { 'EN': 'Available Options', 'ES': 'Opciones Disponibles' },
    'USIN': { 'EN': 'User Information', 'ES': 'Datos del Usuario' },
    'PREF': { 'EN': 'Preferences', 'ES': 'Preferencias' },
    'SECTY': { 'EN': 'Security', 'ES': 'Seguridad' },
    'HELP': { 'EN': 'Help', 'ES': 'Ayuda' },
    'PREF_TX1': { 'EN': 'YOUR POSTS AND ARTICLES ARE PUBLIC', 'ES': 'TUS PUBLICACIONES Y ARTÍCULOS SON PÚBLICOS' },
    'PREF_TX2': { 'EN': 'DISPLAY YOUR EMAIL ADDRESS', 'ES': 'MOSTRAR TU CORREO ELECTRÓNICO' },
    'PREF_TX3': { 'EN': 'DISPLAY YOUR PHONE NUMBER', 'ES': 'MOSTRAR TU NÚMERO DE TELÉFONO' },
    'PREF_TX4': { 'EN': 'YOUR DISPLAYED LANGUAGE', 'ES': 'IDIOMA CONFIGURADO' },
    'PREF_TX5': { 'EN': 'YOUR DISPLAYED PROFILE BACKGROUND', 'ES': 'IMAGEN DE FONDO' },
    'CUS_ACTION': { 'EN': 'Action', 'ES': 'Acción' },
    'CUS_ALLW': { 'EN': 'ALLOWED', 'ES': 'PERMITIDO' },
    'CUS_NALLW': { 'EN': 'NOT ALLOWED', 'ES': 'NO PERMITIDO' },
    'CUS_IMG': { 'EN': 'IMAGE NAME', 'ES': 'IMAGEN' },
    'TIT_SET': { 'EN': 'SETTINGS', 'ES': 'CONFIGURACIÓN' },
    'F_NAME': { 'EN': 'Name', 'ES': 'Nombre' },
    'F_LNAME': { 'EN': 'Last Name', 'ES': 'Apellido' },
    'F_EMAIL': { 'EN': 'Email', 'ES': 'Correo' },
    'F_USER': { 'EN': 'Username', 'ES': 'Usuario' },
    'F_PNUM': { 'EN': 'Phone Number', 'ES': 'Teléfono' },
    'F_DBIR': { 'EN': 'Date of Birth', 'ES': 'Fecha de Nacimiento' },
    'F_SUMM': { 'EN': 'Summary or Intro', 'ES': 'Autobiografía' },
    'F_PCAT': { 'EN': 'Preferred Categories', 'ES': 'Categorías de Interés' },
    'F_SELCAT': { 'EN': 'Select a Category', 'ES': 'Elije una categoría' },
    'F_CHPASS': { 'EN': 'Change your password', 'ES': 'Cambia tu clave' },
    'F_FPASS': { 'EN': 'Password', 'ES': 'Clave' },
    'F_FCPASS': { 'EN': 'Confirm Password', 'ES': 'Confirmar Clave' },
    'F_TXPASS': {
        'EN': 'If you want to change your password, complete the required fields',
        'ES': 'Si deseas cambiar tu clave, completa los campos requeridos.'
    },
    'F_REQUIRED': { 'EN': 'Field Required', 'ES': 'Campo Requerido' },
    'F_UPDPASS': { 'EN': 'UPDATE PASSWORD', 'ES': 'ACTUALIZAR CLAVE' },
    'F_UPDINFO': { 'EN': 'UPDATE INFORMATION', 'ES': 'ACTUALIZAR DATOS' },
    'NOT_ALW_FILE': { 'EN': '"Illegal file type"', 'ES': 'Tipo de archivo no permitido' },
    'PIC_PROF_ERRSIZE': {
        'EN': 'The profile picture should not be larger than 5MB',
        'ES': 'La foto de perfil no debería ser mayor a 5MB.'
    },
    'NOTIF': { 'EN': 'Notification', 'ES': 'Notificación' },
    'CONF_REMOVE_PROFPIC': {
        'EN': 'are you sure to remove profile picture?',
        'ES': '¿estás seguro que deseas remover la foto de perfil?'
    },
    'ERR_ADD_CATG': { 'EN': 'Error adding a category', 'ES': 'Error al agregar una categoría' },
    'ERR_ADD_CATG_TX': { 'EN': 'The selected category has been already added', 'ES': 'La categoría seleccionada ya ha sido agregada' },
    'EMAIL_INVALID': { 'EN': 'The email is invalid. Review and try again', 'ES': 'El correo es inválido. Revise e intente de nuevo.' },
    'REQ_PASS': {
        'EN': 'Please, write your password',
        'ES': 'Por favor, escriba su clave.'
    },
    'REQ_CPASS': {
        'EN': 'Please, confirm your password',
        'ES': 'Por favor, confirme su clave.'
    },
    'PAS_NOMATCH': {
        'EN': 'The passwords do not match. Review and try again',
        'ES': 'Las claves no coinciden. Revise e intente de nuevo.'
    },
    'PAS_LEN': {
        'EN': 'Password must contain between 8 and 15 characters',
        'ES': 'La clave debe tener entre 8 y 15 caracteres.'
    },
    'INFO_UPT': {
        'EN': 'The information has been updated successfully',
        'ES': 'La información ha sido actualizada correctamente.'
    },
    'INFO_NOUPT': {
        'EN': 'The information cannot be updated. Try again later',
        'ES': 'La información no pudo ser actualizada. Intente de nuevo más tarde.'
    },
    'ERR_PROFPIC': {
        'EN': 'Profile picture format is not allowed',
        'ES': 'La foto de perfil tiene un formato no permitido.'
    },
    'EXIST_EMAIL': {
        'EN': 'Email address is already in use',
        'ES': 'El correo electrónico está actualmente en uso.'
    },
    'HELP_TX': {
        'EN': '<p class="lnh">IF YOU NEED ANY HELP, YOU CAN CONTACT US FILLING THE FORM <a class="linke" href="http://site.connectus.global/contact" target="_new">CLICKING HERE</a></p>',
        'ES': '<p class="lnh">SI NECESITAS AYUDA, PUEDES CONTACTARNOS COMPLETANDO EL FORMULARIO HACIENDO <a class="linke" href="http://site.connectus.global/contacto" target="_new">CLIC AQUÍ</a></p>.'
    },
    'FIN_HD': { 'EN': 'Find and discover people in Connectus...', 'ES': 'Busca y encuentra personas en Connectus...' },
    'TOLT_MYMSS': { 'EN': 'MY MESSAGES', 'ES': 'MIS MENSAJES' },
    'TOLT_MYNOTIF': { 'EN': 'MY NOTIFICATIONS', 'ES': 'MIS NOTIFICACIONES' },
    'TOLT_LOGOUT': { 'EN': 'LOGOUT', 'ES': 'SALIR' },
    'HOME': { 'EN': 'HOME', 'ES': 'INICIO' },
    'HOME_RCMART': { 'EN': 'We recommend the following articles...', 'ES': 'Te recomendamos los siguientes artículos...' },
    'CONAWRES': { 'EN': 'Connections waiting response', 'ES': 'Conexiones esperando respuesta' },
    'CONFEED': { 'EN': 'Connectus Feed', 'ES': 'Actividad Connectus' },
    'HOME_INPFEED': { 'EN': 'Share something great in Connectus...', 'ES': 'Comparte algo grandioso en Connectus...' },
    'VIEWMORE': { 'EN': 'View more', 'ES': 'Ver más' },
    'VIEWALL': { 'EN': 'View all', 'ES': 'Ver todos' },
    'ACTCHTX': { 'EN': 'Active Chats', 'ES': 'Chats Activos' },
    'NACTCHTX': { 'EN': 'No active chats', 'ES': 'No hay chats activos' },
    'FNDCONTX': { 'EN': 'Find a connection', 'ES': 'Buscar una conexión' },
    'COMMENTSTX': { 'EN': 'Comments', 'ES': 'Comentarios' },
    'LEAVECOMM': { 'EN': 'Leave a comment', 'ES': 'Deja un comentario' },
    'NEXTNAV': { 'EN': 'Next', 'ES': 'Siguiente' },
    'PREVNAV': { 'EN': 'Previous', 'ES': 'Anterior' },
    'NOCOMMENTSTX': { 'EN': 'No comments', 'ES': 'Sin comentarios' },
    'HLEVENTS': { 'EN': 'Highlighted Events', 'ES': 'Eventos Destacados' },
    'NOEVENTSTX': { 'EN': 'No events to show', 'ES': 'No hay eventos para mostrar' },
    'SELCATG': { 'EN': 'Select a category', 'ES': 'Selecciona una categoría' },
    'TITCATG': { 'EN': 'Title of category', 'ES': 'Título de la categoría' },
    'PICTX': { 'EN': 'Pictures', 'ES': 'Imágenes' },
    'FILESTX': { 'EN': 'Files', 'ES': 'Archivos' },
    'ADDFILESTX': { 'EN': 'Add Files', 'ES': 'Agregar Archivos' },
    'ADDPICTURESTX': { 'EN': 'Add Pictures', 'ES': 'Agregar Imágenes' },
    'SENDTX': { 'EN': 'Send', 'ES': 'Enviar' },
    'POSTEDTX': { 'EN': 'Posted on', 'ES': 'Publicado el' },
    'ATTX': { 'EN': 'at', 'ES': 'a las' },
    'REPORTX': { 'EN': 'Report', 'ES': 'Denunciar' },
    'DELETETX': { 'EN': 'Delete', 'ES': 'Eliminar' },
    'EDITTX': { 'EN': 'Edit', 'ES': 'Editar' },
    'CONFIRMTX': { 'EN': 'Confirm', 'ES': 'Confirmar' },
    'CONFDELPOST': {
        'EN': 'Are you sure to delete the post?',
        'ES': '¿estás seguro de eliminar esta publicación?'
    },
    'CONFREPPOST': {
        'EN': 'Are you sure to report this post?',
        'ES': '¿estás seguro de denunciar esta publicación?'
    },
    'SUCCREPPOST': {
        'EN': 'The post has been reported successfully.',
        'ES': 'La publicación ha sido denunciada correctamente.'
    },
    'DUPREPPOST': {
        'EN': 'You have already reported this post',
        'ES': 'Ya has denunciado esta publicación'
    },
    'ARTICLESTX': { 'EN': 'ARTICLES', 'ES': 'ARTÍCULOS' },
    'NOTIFTX': { 'EN': 'NOTIFICATIONS', 'ES': 'NOTIFICACIONES' },
    'MYPROFTX': { 'EN': 'MY PROFILE', 'ES': 'MI PERFIL' },
    'NORESULTS': { 'EN': 'No results to show', 'ES': 'Sin resultados para mostrar' },
    'ALL': { 'EN': 'ALL', 'ES': 'TODOS' },
    'KEEPREAD': { 'EN': 'Keep Reading', 'ES': 'Seguir Leyendo' },
    'CREATEARTITX': { 'EN': 'Create Article', 'ES': 'Crear Artículo' },
    'CREATEARTITXN': { 'EN': 'CREATE AN ARTICLE', 'ES': 'CREATE UN ARTÍCULO' },
    'ARTADDX': { 'EN': 'Article has been added', 'ES': 'El artículo ha sido agregado' },
    'RETARTIX': { 'EN': 'RETURN TO ARTICLES', 'ES': 'VOLVER A LOS ARTÍCULOS' },
    'ARTITXT': { 'EN': 'Write something interesting...', 'ES': 'Escribe algo interesante...' },
    'CONNREMV': { 'EN': 'Connection has been removed', 'ES': 'La conexión ha sido removida' },
    'CONNACP': { 'EN': 'Connection has been approved', 'ES': 'La conexión ha sido arobada' },
    'CONNREJ': { 'EN': 'Connection has been rejected', 'ES': 'La conexión ha sido rechazada' },
    'CONNCANC': { 'EN': 'Connection has been canceled', 'ES': 'La conexión ha sido cancelada' },
    'CONNTX': { 'EN': 'CONNECTIONS', 'ES': 'CONEXIONES' },
    'MYCONNTX': { 'EN': 'My connections', 'ES': 'Mis conexiones' },
    'CONNAWARES': { 'EN': 'Connections Awaiting Response', 'ES': 'Conexiones Esperando Respuesta' },
    'CONNSENT': { 'EN': 'Connections Requests Sent', 'ES': 'Solicitudes de Conexiones Enviadas' },
    'FINDCONTX': { 'EN': 'Find a connection', 'ES': 'Buscar una conexión' },
    'APPROTX': { 'EN': 'APPROVE', 'ES': 'APROBAR' },
    'REJECTX': { 'EN': 'REJECT', 'ES': 'RECHAZAR' },
    'REMVTX': { 'EN': 'REMOVE', 'ES': 'REMOVE' },
    'CANCELRTX': { 'EN': 'CANCEL REQUEST', 'ES': 'CANCELAR SOLICITUD' },
    'ARTSUG': { 'EN': 'Articles Suggestions', 'ES': 'Artículos Sugeridos' },
    'EVENTSTX': { 'EN': 'EVENTS', 'ES': 'EVENTOS' },
    'MESSAGINGTX': { 'EN': 'MESSAGING', 'ES': 'MENSAJERÍA' },
    'FOOTER': {
        'EN': 'Connectus Global. All rights are reserved. Copyright &copy;2021',
        'ES': 'Connectus Global. Todos los derechos reservados. Copyright &copy;2021'
    },
    'MESSAGESENTX': { 'EN': 'Message sent!', 'ES': '¡Mensaje enviado!' },
    'CLOSECHATTX': { 'EN': 'Are you sure to close the chat', 'ES': '¿Estás seguro de cerrar el chat?' },
    'FINDCONCHAT': { 'EN': 'Find a connection and start messaging', 'ES': 'Busca una conexión y comienza a chatear' },
    'LEAVECHAT': { 'EN': 'Leave a message', 'ES': 'Escribe un mensaje' },
    'DOWNLCONTTX': { 'EN': 'DOWNLOADABLE CONTENT', 'ES': 'CONTENIDO DESCARGABLE' },
    'RETURN': { 'EN': 'RETURN', 'ES': 'VOLVER' },
    'RETURNHOME': { 'EN': 'RETURN TO HOME', 'ES': 'REGREGAR AL HOME' },
    'USERNOTFOUND': { 'EN': 'The user was not found', 'ES': 'El usuario no fue encontrado' },
    'CONNECT': { 'EN': 'CONNECT', 'ES': 'CONECTAR' },
    'CANCELREQCON': { 'EN': 'CANCEL REQUEST CONNECTION', 'ES': 'CANCELAR SOLICITUD DE CONEXIÓN' },
    'AWAREQCON': { 'EN': 'AWAITING RESPONSE CONNECTION', 'ES': 'ESPERANDO RESPUESTA DE CONEXIÓN' },
    'REJECTCON': { 'EN': 'REJECT CONNECTION', 'ES': 'RECHAZAR CONEXIÓN' },
    'ACCEPTCON': { 'EN': 'ACCEPT CONNECTION', 'ES': 'ACEPTAR CONEXIÓN' },
    'REMOVECON': { 'EN': 'REMOVE CONNECTION', 'ES': 'REMOVER CONEXIÓN' },
    'CONNECTEDX': { 'EN': 'CONNECTED', 'ES': 'CONECTADO' },
    'CONNECTIONSTX': { 'EN': 'Connections', 'ES': 'Conexiones' },
    'MEMBERSINCE': { 'EN': 'Member since', 'ES': 'Miembro desde' },
    'EMAILADDR': { 'EN': 'EMAIL ADDRESS', 'ES': 'CORREO ELECTRÓNICO' },
    'PHONENUMB': { 'EN': 'PHONE NUMBER', 'ES': 'TELÉFONO' },
    'INTERCATG': { 'EN': 'INTERESTED CATEGORIES', 'ES': 'CATEGORÍAS DE INTERÉS' },
    'POSTDEL': { 'EN': 'POST DELETED', 'ES': 'PUBLICACIÓN ELIMINADA' },
    'NOTACCON': { 'EN': 'HAS ACCEPTED YOUR CONNECTION REQUEST', 'ES': 'HA ACEPTADO TU SOLICITUD DE CONEXIÓN' },
    'NOTREJCON': { 'EN': 'HAS REJECTED YOUR CONNECTION REQUEST ', 'ES': 'HA RECHAZADO TU SOLICITUD DE CONEXIÓN' },
    'NOTANLCON': { 'EN': 'HAS CANCELED THE CONNECTION REQUEST ', 'ES': 'HA CANCELADO LA SOLICITUD DE CONEXIÓN' },
    'NOTNEWCON': { 'EN': 'HAS SENT YOU A CONNECTION REQUEST ', 'ES': 'TE HA ENVIADO UNA SOLICITUD DE CONEXIÓN' },
    'NOTREMCON': { 'EN': 'HAS REMOVED YOU FROM CONNECTIONS LIST ', 'ES': 'TE HA REMOVIDO DE SU LISTA DE CONEXIONES' },
    'NOTREMALL': { 'EN': 'REMOVE ALL NOTIFICATIONS ', 'ES': 'REMOVER TODAS LAS NOTIFICACIONES' },
    'NONOT': { 'EN': 'There are no notifications at this time. ', 'ES': 'Sin notificaciones por los momentos.' },
    'LOGCON': { 'EN': 'LOG IN CONNECTUS', 'ES': 'INGRESA A CONNECTUS' },
    'LOGUSEMAIL': { 'EN': 'USERNAME OR EMAIL', 'ES': 'USUARIO O CORREO' },
    'LOGPASS': { 'EN': 'PASSWORD', 'ES': 'CLAVE' },
    'LOGLOGIN': { 'EN': 'LOGIN', 'ES': 'ENTRAR' },
    'LOGFOGPASS': { 'EN': 'FORGOT PASSWORD?', 'ES': 'OLVIDASTE TU CLAVE?' },
    'LOGNOAC': { 'EN': `DON'T HAVE AN ACCOUNT YET?`, 'ES': '¿AÚN NO TIENES CUENTA?' },
    'LOGCACC': { 'EN': 'CREATE ACCOUNT', 'ES': 'CREA UNA CUENTA' },
    'LOGREGTX': { 'EN': 'REGISTER AND BE PART OF SOMETHING GREAT', 'ES': 'RÉGISTRATE Y SE PARTE DE ALGO EXTRAORDINARIO' },
    'LOGNAMETX': { 'EN': 'NAME', 'ES': 'NOMBRE' },
    'LOGLNAMETX': { 'EN': 'LAST NAME', 'ES': 'APELLIDO' },
    'LOGEMAILTX': { 'EN': 'EMAIL', 'ES': 'CORREO' },
    'LOGEMAILEREQ': { 'EN': 'Email is required', 'ES': 'El correo es requerido' },
    'LOGEMAILINV': { 'EN': 'Email is invalid', 'ES': 'El correo es inválido' },
    'LOGUSERNTX': { 'EN': 'USERNAME', 'ES': 'USUARIO' },
    'LOGPASSTX': { 'EN': 'PASSWORD', 'ES': 'CLAVE' },
    'LOGUSERREQ': { 'EN': 'Username is required', 'ES': 'El usuario es requerido' },
    'LOGUSERREQ2': { 'EN': 'Username o Email is required', 'ES': 'El usuario o correo es requerido' },
    'LOGPASSERR': { 'EN': 'The password must contain between 8 and 15 characters', 'ES': 'La clave debe tener entre 8 a 15 caracteres' },
    'LOGRESPASS': { 'EN': 'RECOVER YOUR PASSWORD', 'ES': 'RECUPERAR CLAVE' },
    'LOGPASSCHANGED': { 'EN': 'YOUR PASSWORD HAS BEEN CHANGED SUCCESSFULLY', 'ES': 'LA CLAVE HA SIDO CAMBIADA CORRECTAMENTE' },
    'LOGPASSCHUSER': { 'EN': 'WRITE YOUR USERNAME OR EMAIL', 'ES': 'ESCRIBE TU USUARIO O CORREO' },
    'LOGPASSCHCODE': { 'EN': 'WRITE THE VALIDATION CODE SENT TO YOUR EMAIL', 'ES': 'INDICA EL CÓDIGO DE VALIDACIÓN ENVIADO A TU CORREO' },
    'LOGPASSCHPASS': { 'EN': 'NEW PASSWORD', 'ES': 'NUEVA CLAVE' },
    'LOGPASSCHCPASS': { 'EN': 'CONFIRM NEW PASSWORD', 'ES': 'CONFIRMA NUEVA CLAVE' },
    'LOGPASSRET': { 'EN': 'RETURN', 'ES': 'REGRESAR' },
    'GOLOGIN': { 'EN': 'GO TO LOGIN', 'ES': 'VOLVER AL LOGIN' },
    'LOGREGCON': { 'EN': 'REGISTER AND CONNECT', 'ES': 'REGÍSTRATE Y CONÉCTATE' },
    'LOGACLOCKED': { 'EN': 'ACCOUNT IS LOCKED', 'ES': 'CUENTA BLOQUEADA' },
    'LOGACERRPASS': { 'EN': 'WRONG USERNAME OR PASSWORD', 'ES': 'USUARIO O CLAVE INCORRECTOS' },
    'LOGERRVALID': { 'EN': 'USERNAME COULD NOT BE VALIDATED. TRY AGAIN LATER', 'ES': 'USUARIO NO PUDO SER VALIDADO. INTENTE MÁS TARDE' },
    'LOGERRNOTLOG': { 'EN': 'CANNOT LOGIN NOW. TRY AGAIN LATER', 'ES': 'NO SE PUEDE INGRESAR. INTENTE MÁS TARDE.' },
    'LOGERRNOTREG': { 'EN': 'CANNOT REGISTER NOW. TRY AGAIN LATER', 'ES': 'NO SE PUEDE REGISTRAR. INTENTE MÁS TARDE.' },
    'REGUSERNO': { 'EN': 'USERNAME IS NOT AVAILABLE. USE ANOTHER ONE', 'ES': 'USUARIO YA EXISTE. UTILICE OTRO.' },
    'REGEMAILNO': { 'EN': 'EMAIL IS NOT AVAILABLE. USE ANOTHER ONE', 'ES': 'CORREO YA EXISTE. UTILICE OTRO.' },
    'REGRECPERR': { 'EN': 'REQUEST COULD NOT BE VALIDATED. TRY AGAIN LATER', 'ES': 'NO SE PUDO PROCESAR LA SOLICITUD. INTENTE MÁS TARDE.' },
    'BTNVALIDCODE': { 'EN': 'VALIDATE CODE', 'ES': 'VALIDAR CÓDIGO' },
    'RECPASSNOF': { 'EN': 'EMAIL OR USERNAME WAS NOT FOUND. TRY AGAIN', 'ES': 'USUARIO O CORREO NO FUE ENCONTRADO. INTENTE NUEVAMENTE' },
    'ERRRECPASS': { 'EN': 'CANNOT RECOVER PASSWORD NOW. TRY AGAIN LATER', 'ES': 'NO SE PUDO RECUPERAR LA CLAVE. INTENTE MÁS TARDE.' },
    'VALIDCODEREQ': { 'EN': 'VALIDATION CODE IS REQUIRED. TRY AGAIN.', 'ES': 'CÓDIGO DE VALIDACIÓN ES REQUERIDO. INTENTE NUEVAMENTE.' },
    'BTNCHPASS': { 'EN': 'CHANGE PASSWORD', 'ES': 'CAMBIAR CLAVE' },
    'VALIDCODEERR': { 'EN': 'VALIDATION CODE IS WRONG. TRY AGAIN.', 'ES': 'CÓDIGO DE VALIDACIÓN ES INCORRECTO. INTENTE NUEVAMENTE.' },
    'NOVALIDCODEERR': { 'EN': 'CANNOT VALIDATE THE CODE NOW. TRY AGAIN LATER.', 'ES': 'NO SE PUEDE VALIDAR EL CÓDIGO. INTENTE MÁS TARDE.' },
    'RECPASSREQ': { 'EN': 'PASSWORD IS REQUIRED. TRY AGAIN.', 'ES': 'LA CLAVE ES REQUERIDA. INTENTE NUEVAMENTE.' },
    'RECCPASS': { 'EN': 'CONFIRM YOUR PASSWORD', 'ES': 'CONFIRMA TU CLAVE' },
    'PASSNOMATCH': { 'EN': 'PASSWORDS DO NOT MATCH. TRY AGAIN', 'ES': 'CLAVES NO COINCIDEN. INTENTE NUEVAMENTE.' },
    'ERRCHPASS': { 'EN': 'CANNOT CHANGE THE PASSWORD NOW. TRY AGAIN LATER', 'ES': 'NO SE PUEDE CAMBIAR LA CLAVE. INTENTE MÁS TARDE.' },




}